In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
previous_position = np.array([0.5,0.75,1.25,1.5]).reshape(-1,1)
binomial_moves = np.array([50,-50]).reshape(-1,1)
previous_pnl = np.array([87.5,12.5,12.5,-112.5]).reshape(-1,1)

In [3]:
print(np.shape(previous_position),np.shape(binomial_moves),np.shape(previous_pnl))

(4, 1) (2, 1) (4, 1)


In [4]:
(np.dot(previous_position,np.transpose(binomial_moves)) + previous_pnl)

array([[ 112.5,   62.5],
       [  50. ,  -25. ],
       [  75. ,  -50. ],
       [ -37.5, -187.5]])

In [5]:
next_pnl = (np.dot(previous_position,np.transpose(binomial_moves)) + previous_pnl).reshape(-1,1)

In [6]:
next_pnl

array([[ 112.5],
       [  62.5],
       [  50. ],
       [ -25. ],
       [  75. ],
       [ -50. ],
       [ -37.5],
       [-187.5]])

In [7]:
def current_pnl(previous_position,binomial_moves,previous_pnl):
    previous_position = previous_position.reshape(-1,1)
    binomial_moves = binomial_moves.reshape(-1,1)
    previous_pnl = previous_pnl.reshape(-1,1)
    
    return (np.dot(previous_position,np.transpose(binomial_moves)) + previous_pnl).reshape(-1,1)

In [8]:
def current_position(previous_position,buy_size,sell_size):
    lot_size = np.array([-sell_size,buy_size]).reshape(-1,1)
    previous_position = previous_position.reshape(-1,1)
    return (previous_position + np.transpose(lot_size)).reshape(-1,1)


In [9]:
previous_position = np.array([0.75,1.25]).reshape(-1,1)
buy_size = 0.25
sell_size = 0.25

In [10]:
current_position(previous_position,buy_size,sell_size)

array([[0.5],
       [1. ],
       [1. ],
       [1.5]])

In [11]:
def time_step(previous_position,binomial_moves,previous_pnl,buy_size,sell_size):
    return current_position(previous_position,buy_size,sell_size),current_pnl(previous_position,binomial_moves,previous_pnl)

In [16]:
previous_pnl = np.array([0])
previous_position = np.array([1])
for i in range (0,3):
    previous_position,previous_pnl = time_step(previous_position,binomial_moves,previous_pnl,buy_size,sell_size)
print(previous_position)
print(previous_pnl)

[[  250000]
 [ 6750000]
 [ 6750000]
 [13250000]
 [ 6750000]
 [13250000]
 [13250000]
 [19750000]]
[[  112500000]
 [   62500000]
 [  362500000]
 [ -337500000]
 [  662500000]
 [  -37500000]
 [  262500000]
 [-1087500000]]


In [13]:
bet_increase_ratio = 5

In [22]:

previous_pnl = np.array([0])
previous_position = np.array([1000000])
buy_size = 250000
sell_size = 250000
binomial_moves = np.array([50,-50]).reshape(-1,1)/10000
for i in range (0,3):
    if i>=1:
        buy_size = buy_size * bet_increase_ratio
        #sell_size = sell_size/bet_increase_ratio
    pos = previous_position
    previous_position,previous_pnl = time_step(pos,binomial_moves,previous_pnl,buy_size,sell_size)

print(pos)
print(previous_pnl)

[[ 500000]
 [2000000]
 [1000000]
 [2500000]]
[[ 11250.]
 [  6250.]
 [ 11250.]
 [ -8750.]
 [  6250.]
 [ -3750.]
 [  1250.]
 [-23750.]]


In [23]:
expectation = np.sum(previous_pnl)/len(previous_pnl)
print('expected value:-', expectation)
# number of instances where pnl is positive/ total number of instances
profit = np.where(previous_pnl>0,1,0)
pop = np.sum(profit)/len(profit)
print('probability of profit:- ',pop*100,'%')

expected value:- 0.0
probability of profit:-  62.5 %
